#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.15.779.0000
//
//   fxc shaders_dx9.psh /nologo /Tps_1_4 /LD /EshaderYellowBlueAnaglyph
//    /FhShaders_dx9\shaderYellowBlueAnaglyph.h
//
//
// Parameters:
//
//   sampler2D sL;
//   sampler2D sR;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   sL           s0       1
//   sR           s1       1
//

    ps_1_4
    texld r0, t0
    texld r1, t0
    mov r0.xy, r0
    mov r0.zw, r1

// approximately 4 instruction slots used (2 texture, 2 arithmetic)
#endif

const BYTE g_ps14_shaderYellowBlueAnaglyph[] =
{
      4,   1, 255, 255, 254, 255, 
     38,   0,  67,  84,  65,  66, 
     28,   0,   0,   0,  98,   0, 
      0,   0,   4,   1, 255, 255, 
      2,   0,   0,   0,  28,   0, 
      0,   0,   0,   1,   0,   0, 
     91,   0,   0,   0,  68,   0, 
      0,   0,   3,   0,   0,   0, 
      1,   0,   0,   0,  72,   0, 
      0,   0,   0,   0,   0,   0, 
     88,   0,   0,   0,   3,   0, 
      1,   0,   1,   0,   0,   0, 
     72,   0,   0,   0,   0,   0, 
      0,   0, 115,  76,   0, 171, 
      4,   0,  12,   0,   1,   0, 
      1,   0,   1,   0,   0,   0, 
      0,   0,   0,   0, 115,  82, 
      0, 112, 115,  95,  49,  95, 
     52,   0,  77, 105,  99, 114, 
    111, 115, 111, 102, 116,  32, 
     40,  82,  41,  32,  68,  51, 
     68,  88,  57,  32,  83, 104, 
     97, 100, 101, 114,  32,  67, 
    111, 109, 112, 105, 108, 101, 
    114,  32,  57,  46,  49,  53, 
     46,  55,  55,  57,  46,  48, 
     48,  48,  48,   0,  66,   0, 
      0,   0,   0,   0,  15, 128, 
      0,   0, 228, 176,  66,   0, 
      0,   0,   1,   0,  15, 128, 
      0,   0, 228, 176,   1,   0, 
      0,   0,   0,   0,   3, 128, 
      0,   0, 228, 128,   1,   0, 
      0,   0,   0,   0,  12, 128, 
      1,   0, 228, 128, 255, 255, 
      0,   0
};
